In [40]:
#%matplotlib inline
import pandas as pd
#import matplotlib.pyplot as plt
import numpy as np
#import sklearn
#import sklearn.datasets
#from numpy.random import seed
#seed(1)

In [2]:
# Read the csv file into a pandas DataFrame
file = "dems.csv"
primary_data = pd.read_csv(file)
primary_data.head()

fips  % Foreign Born  Veterans  Mean Travel Time  Median Household Income  \
0  1001             1.6      5922              26.2                    53682   
1  1003             3.6     19346              25.9                    50221   
2  1005             2.9      2120              24.6                    32911   
3  1007             1.2      1327              27.6                    36447   
4  1009             4.3      4540              33.9                    44145   

   Below Poverty Level  Total Number of Firms  % Black-owned Firms  \
0                 12.1                   4067                 15.2   
1                 13.9                  19035                  2.7   
2                 26.7                   1667                  0.0   
3                 18.1                   1385                 14.9   
4                 15.8                   4458                  0.0   

   % Asian-owned Firms  % Hispanic-owned Firms  % Women-owned Firms  \
0                  1.3                     0.7                 31.7   
1                  1.0                     1.3                 27.3   
2                  0.0                     0.0                 27.0   
3                  0.0                     0.0                  0.0   
4                  0.0                     0.0                 23.2   

   Manufacturers Shipments ($1000)  Retail Sales ($1000)  \
0                                0                598175   
1                          1410273               2966489   
2                                0                188337   
3                                0                124707   
4                           341544                319700   

   Retail Sales per Capita  Building permits  Population per Square Mile  \
0                    12003               131                        91.8   
1                    17166              1384                       114.6   
2                     6334                 8                        31.0   
3                     5804                19                        36.8   
4                     5622                 3                        88.9   

   Bernie Sanders  Hillary Clinton                    Most Votes  
0             544             2387  ('Votes', 'Hillary Clinton')  
1            2694             5290  ('Votes', 'Hillary Clinton')  
2             222             2567  ('Votes', 'Hillary Clinton')  
3             246              942  ('Votes', 'Hillary Clinton')  
4             395              564  ('Votes', 'Hillary Clinton')

In [3]:
file2 = "reps.csv"
primary_data2 = pd.read_csv(file2)
primary_data2.head()

fips  % Foreign Born  Veterans  Mean Travel Time  Median Household Income  \
0  1001             1.6      5922              26.2                    53682   
1  1003             3.6     19346              25.9                    50221   
2  1005             2.9      2120              24.6                    32911   
3  1007             1.2      1327              27.6                    36447   
4  1009             4.3      4540              33.9                    44145   

   Below Poverty Level  Total Number of Firms  % Black-owned Firms  \
0                 12.1                   4067                 15.2   
1                 13.9                  19035                  2.7   
2                 26.7                   1667                  0.0   
3                 18.1                   1385                 14.9   
4                 15.8                   4458                  0.0   

   % Asian-owned Firms  % Hispanic-owned Firms            ...              \
0                  1.3                     0.7            ...               
1                  1.0                     1.3            ...               
2                  0.0                     0.0            ...               
3                  0.0                     0.0            ...               
4                  0.0                     0.0            ...               

   Chris Christie  Donald Trump  Jeb Bush  John Kasich  Marco Rubio  \
0               0          5387         0          421         1785   
1               0         23618         0         2987         9703   
2               0          1710         0          123          498   
3               0          1959         0           84          444   
4               0          7390         0          337         1843   

   Mike Huckabee  Rand Paul  Rick Santorum  Ted Cruz  \
0              0          0              0      2482   
1              0          0              0      8571   
2              0          0              0       609   
3              0          0              0      1011   
4              0          0              0      3698   

                  Most Votes  
0  ('Votes', 'Donald Trump')  
1  ('Votes', 'Donald Trump')  
2  ('Votes', 'Donald Trump')  
3  ('Votes', 'Donald Trump')  
4  ('Votes', 'Donald Trump')  

[5 rows x 28 columns]

In [4]:
primary_data.columns

Index(['fips', '% Foreign Born', 'Veterans', 'Mean Travel Time',
       'Median Household Income', 'Below Poverty Level',
       'Total Number of Firms', '% Black-owned Firms', '% Asian-owned Firms',
       '% Hispanic-owned Firms', '% Women-owned Firms',
       'Manufacturers Shipments ($1000)', 'Retail Sales ($1000)',
       'Retail Sales per Capita', 'Building permits',
       'Population per Square Mile', 'Bernie Sanders', 'Hillary Clinton',
       'Most Votes'],
      dtype='object')

In [5]:
primary_data2.columns

Index(['fips', '% Foreign Born', 'Veterans', 'Mean Travel Time',
       'Median Household Income', 'Below Poverty Level',
       'Total Number of Firms', '% Black-owned Firms', '% Asian-owned Firms',
       '% Hispanic-owned Firms', '% Women-owned Firms',
       'Manufacturers Shipments ($1000)', 'Retail Sales ($1000)',
       'Retail Sales per Capita', 'Building permits',
       'Population per Square Mile', 'Ben Carson', 'Carly Fiorina',
       'Chris Christie', 'Donald Trump', 'Jeb Bush', 'John Kasich',
       'Marco Rubio', 'Mike Huckabee', 'Rand Paul', 'Rick Santorum',
       'Ted Cruz', 'Most Votes'],
      dtype='object')

In [6]:
 #Assign X (data) and y (target)

## BEGIN SOLUTION
X2 = primary_data2[['% Foreign Born', 'Veterans', 'Mean Travel Time',
       'Median Household Income', 'Below Poverty Level',
       'Total Number of Firms', '% Black-owned Firms', '% Asian-owned Firms',
       '% Hispanic-owned Firms', '% Women-owned Firms',
       'Manufacturers Shipments ($1000)', 'Retail Sales ($1000)',
       'Retail Sales per Capita', 'Building permits',
       'Population per Square Mile']]
y2 = primary_data2[['Most Votes']]
print(X2.shape, y2.shape)
### END SOLUTION

(2711, 15) (2711, 1)


In [7]:
# Assign X (data) and y (target)

## BEGIN SOLUTION
X = primary_data[['% Foreign Born', 'Veterans', 'Mean Travel Time',
       'Median Household Income', 'Below Poverty Level',
       'Total Number of Firms', '% Black-owned Firms', '% Asian-owned Firms',
       '% Hispanic-owned Firms', '% Women-owned Firms',
       'Manufacturers Shipments ($1000)', 'Retail Sales ($1000)',
       'Retail Sales per Capita', 'Building permits',
       'Population per Square Mile']]
y = primary_data[['Most Votes']]
print(X.shape, y.shape)
### END SOLUTION

(2798, 15) (2798, 1)


In [8]:
from sklearn.preprocessing import LabelEncoder

# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder2 = LabelEncoder()
label_encoder.fit(y)
label_encoder2.fit(y2)
encoded_y = label_encoder.transform(y)
encoded_y2 = label_encoder2.transform(y2)

C:\Users\cobin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\cobin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
for label, original_class in zip(encoded_y, y):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

Original Class: Most Votes
Encoded Label: 2
------------


In [10]:
for label, original_class in zip(encoded_y2, y2):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

Original Class: Most Votes
Encoded Label: 1
------------


In [11]:
print(X.shape, y.shape)

(2798, 15) (2798, 1)


In [12]:
print(X2.shape, y2.shape)

(2711, 15) (2711, 1)


In [13]:
# Split the data into training and testing

### BEGIN SOLUTION
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, encoded_y, random_state=10)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, encoded_y2, random_state=10)
### END SOLUTION

In [14]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScater model and fit it to the training data
X_scaler = StandardScaler().fit(X_train)
X_scaler2 = StandardScaler().fit(X_train2)

C:\Users\cobin\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\cobin\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


In [15]:
# Transform the training and testing data using the X_scaler

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
X_train_scaled2 = X_scaler2.transform(X_train2)
X_test_scaled2 = X_scaler2.transform(X_test2)

C:\Users\cobin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\cobin\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.
C:\Users\cobin\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  """
C:\Users\cobin\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  


In [37]:
# from sklearn.preprocessing import LabelEncoder

# # Step 1: Label-encode data set
# label_encoder = LabelEncoder()
# label_encoder.fit(y)
# encoded_y = label_encoder.transform(y)
label_encoder.inverse_transform(y_test)

array(["('Votes', 'Hillary Clinton')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'H

In [17]:
from keras.utils import to_categorical

# Step 2: One-hot encoding
y_test_categorical = to_categorical(y_test)
one_hot_y = to_categorical(y_train)
one_hot_y


Using TensorFlow backend.


array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

In [18]:
y_test_categorical2 = to_categorical(y_test2)
one_hot_y2 = to_categorical(y_train2)
one_hot_y2


array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], dtype=float32)

In [19]:
# from keras.utils import to_categorical

# #One-hot encoding
# y_train_categorical = to_categorical(y_train)
# y_test_categorical = to_categorical(y_test)

In [20]:
# first, create a normal neural network with 2 inputs, 6 hidden nodes, and 2 outputs
from keras.models import Sequential
from keras.layers import Dense

# model = Sequential()
# model.add(Dense(units=20, activation='relu', input_dim=14))
# model.add(Dense(units=2, activation='softmax'))

In [21]:
# model.summary()

In [22]:
# # Compile the model
# model.compile(optimizer='adam',
#               loss='categorical_crossentropy',
#               metrics=['accuracy'])

In [23]:
# # Fit the model to the training data
# model.fit(
#     X_train_scaled,
#     y_train,
#     epochs=50,
#     shuffle=True,
#     verbose=2
# )

# Deep Learning
For this network, we simply add an additional hidden layer of 6 nodes

In [24]:
deep_model = Sequential()
deep_model.add(Dense(units=500, activation='relu', input_dim=15))
deep_model.add(Dense(units=400, activation='relu'))
deep_model.add(Dense(units=300, activation='relu'))
deep_model.add(Dense(units=200, activation='relu'))
deep_model.add(Dense(units=100, activation='relu'))
deep_model.add(Dense(units=3, activation='softmax'))

Instructions for updating:
Colocations handled automatically by placer.


In [25]:
deep_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 500)               8000      
_________________________________________________________________
dense_2 (Dense)              (None, 400)               200400    
_________________________________________________________________
dense_3 (Dense)              (None, 300)               120300    
_________________________________________________________________
dense_4 (Dense)              (None, 200)               60200     
_________________________________________________________________
dense_5 (Dense)              (None, 100)               20100     
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 303       
Total params: 409,303
Trainable params: 409,303
Non-trainable params: 0
_________________________________________________________________


In [26]:
deep_model.compile(optimizer='adam',
                   loss='categorical_crossentropy',
                   metrics=['accuracy'])

deep_model.fit(
    X_train_scaled,
    one_hot_y,
    epochs=80,
    shuffle=True,
    verbose=2
)

Instructions for updating:
Use tf.cast instead.
Epoch 1/80
 - 1s - loss: 0.6574 - acc: 0.6463
Epoch 2/80
 - 0s - loss: 0.5893 - acc: 0.6835
Epoch 3/80
 - 0s - loss: 0.5710 - acc: 0.6868
Epoch 4/80
 - 0s - loss: 0.5535 - acc: 0.7164
Epoch 5/80
 - 0s - loss: 0.5507 - acc: 0.7131
Epoch 6/80
 - 0s - loss: 0.5391 - acc: 0.7193
Epoch 7/80
 - 0s - loss: 0.5270 - acc: 0.7278
Epoch 8/80
 - 0s - loss: 0.5286 - acc: 0.7297
Epoch 9/80
 - 0s - loss: 0.5104 - acc: 0.7312
Epoch 10/80
 - 0s - loss: 0.5019 - acc: 0.7421
Epoch 11/80
 - 0s - loss: 0.4963 - acc: 0.7512
Epoch 12/80
 - 0s - loss: 0.4834 - acc: 0.7541
Epoch 13/80
 - 0s - loss: 0.4781 - acc: 0.7479
Epoch 14/80
 - 0s - loss: 0.4658 - acc: 0.7626
Epoch 15/80
 - 0s - loss: 0.4590 - acc: 0.7626
Epoch 16/80
 - 0s - loss: 0.4702 - acc: 0.7579
Epoch 17/80
 - 0s - loss: 0.4387 - acc: 0.7745
Epoch 18/80
 - 0s - loss: 0.4264 - acc: 0.7788
Epoch 19/80
 - 0s - loss: 0.4283 - acc: 0.7898
Epoch 20/80
 - 0s - loss: 0.4183 - acc: 0.7908
Epoch 21/80
 - 0s - l

In [27]:
deep_model2 = Sequential()
deep_model2.add(Dense(units=500, activation='relu', input_dim=15))
deep_model2.add(Dense(units=400, activation='relu'))
deep_model2.add(Dense(units=300, activation='relu'))
deep_model2.add(Dense(units=200, activation='relu'))
deep_model2.add(Dense(units=100, activation='relu'))
deep_model2.add(Dense(units=5, activation='softmax'))

In [28]:
deep_model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 500)               8000      
_________________________________________________________________
dense_8 (Dense)              (None, 400)               200400    
_________________________________________________________________
dense_9 (Dense)              (None, 300)               120300    
_________________________________________________________________
dense_10 (Dense)             (None, 200)               60200     
_________________________________________________________________
dense_11 (Dense)             (None, 100)               20100     
_________________________________________________________________
dense_12 (Dense)             (None, 5)                 505       
Total params: 409,505
Trainable params: 409,505
Non-trainable params: 0
_________________________________________________________________


In [29]:
deep_model2.compile(optimizer='adam',
                   loss='categorical_crossentropy',
                   metrics=['accuracy'])

deep_model2.fit(
    X_train_scaled2,
    one_hot_y2,
    epochs=200,
    shuffle=True,
    verbose=2
)

Epoch 1/200
 - 1s - loss: 0.7589 - acc: 0.7290
Epoch 2/200
 - 0s - loss: 0.6277 - acc: 0.7541
Epoch 3/200
 - 0s - loss: 0.6018 - acc: 0.7595
Epoch 4/200
 - 0s - loss: 0.5619 - acc: 0.7668
Epoch 5/200
 - 0s - loss: 0.5536 - acc: 0.7772
Epoch 6/200
 - 0s - loss: 0.5544 - acc: 0.7698
Epoch 7/200
 - 0s - loss: 0.5323 - acc: 0.7821
Epoch 8/200
 - 0s - loss: 0.5044 - acc: 0.7880
Epoch 9/200
 - 0s - loss: 0.4889 - acc: 0.7890
Epoch 10/200
 - 0s - loss: 0.4787 - acc: 0.7998
Epoch 11/200
 - 0s - loss: 0.4724 - acc: 0.7988
Epoch 12/200
 - 0s - loss: 0.4684 - acc: 0.7993
Epoch 13/200
 - 0s - loss: 0.4603 - acc: 0.8057
Epoch 14/200
 - 0s - loss: 0.4460 - acc: 0.8126
Epoch 15/200
 - 0s - loss: 0.4426 - acc: 0.8131
Epoch 16/200
 - 0s - loss: 0.4282 - acc: 0.8180
Epoch 17/200
 - 0s - loss: 0.4019 - acc: 0.8283
Epoch 18/200
 - 0s - loss: 0.4142 - acc: 0.8259
Epoch 19/200
 - 0s - loss: 0.3905 - acc: 0.8347
Epoch 20/200
 - 0s - loss: 0.3946 - acc: 0.8269
Epoch 21/200
 - 0s - loss: 0.3644 - acc: 0.8490
E

Epoch 171/200
 - 0s - loss: 0.0395 - acc: 0.9877
Epoch 172/200
 - 0s - loss: 0.0562 - acc: 0.9902
Epoch 173/200
 - 0s - loss: 0.0157 - acc: 0.9951
Epoch 174/200
 - 0s - loss: 0.0117 - acc: 0.9966
Epoch 175/200
 - 0s - loss: 0.0124 - acc: 0.9961
Epoch 176/200
 - 0s - loss: 0.0319 - acc: 0.9916
Epoch 177/200
 - 0s - loss: 0.0455 - acc: 0.9857
Epoch 178/200
 - 0s - loss: 0.0149 - acc: 0.9941
Epoch 179/200
 - 0s - loss: 0.0173 - acc: 0.9946
Epoch 180/200
 - 0s - loss: 0.0147 - acc: 0.9961
Epoch 181/200
 - 0s - loss: 0.0467 - acc: 0.9867
Epoch 182/200
 - 0s - loss: 0.0457 - acc: 0.9852
Epoch 183/200
 - 0s - loss: 0.0267 - acc: 0.9897
Epoch 184/200
 - 0s - loss: 0.0345 - acc: 0.9907
Epoch 185/200
 - 0s - loss: 0.0153 - acc: 0.9941
Epoch 186/200
 - 0s - loss: 0.0295 - acc: 0.9931
Epoch 187/200
 - 0s - loss: 0.0381 - acc: 0.9862
Epoch 188/200
 - 0s - loss: 0.0187 - acc: 0.9956
Epoch 189/200
 - 0s - loss: 0.0123 - acc: 0.9961
Epoch 190/200
 - 0s - loss: 0.0030 - acc: 0.9995
Epoch 191/200
 - 0s 

# Compare the models below

# Reps

In [30]:
model_loss, model_accuracy = deep_model2.evaluate(
    X_test_scaled2, y_test_categorical2, verbose=2)
print(
    f"Republican Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Republican Neural Network - Loss: 2.8200067897110213, Accuracy: 0.7109144542772862


In [57]:
deep_model2.predict(X_test_scaled2)[10]

array([3.4671015e-33, 1.2339010e-18, 2.3288368e-27, 2.6662636e-31,
       1.0000000e+00], dtype=float32)

In [58]:
one_hot_y2[10]

array([0., 1., 0., 0., 0.], dtype=float32)

# Dems

In [33]:
model_loss, model_accuracy = deep_model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(f"Democrat Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Democrat Neural Network - Loss: 2.1664486946378436, Accuracy: 0.640000000340598


In [56]:
label_encoder.inverse_transform(np.argmax(deep_model.predict(X_test_scaled), axis=1))

array(["('Votes', 'Hillary Clinton')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Hillary Clinton')",
       "('Votes'

In [53]:
np.argmax(deep_model.predict(X_test_scaled), axis=1)

array([2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1,
       2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1,
       2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2,
       1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2,
       1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1,
       2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1,
       2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1,
       1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 2,
       2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 2, 1,
       1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2,
       2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1,

In [35]:
one_hot_y.

SyntaxError: invalid syntax (<ipython-input-35-df469b4a1cec>, line 1)

# In a nutshell...

![stack more layers](../Images/stack-more-layers.jpg)