In [1]:
import pandas as pd
import numpy as np

# Pre-Processing

In [2]:
# Read the csv file into a pandas DataFrame
file = "dems.csv"
primary_data = pd.read_csv(file)
primary_data.head()

fips  % Foreign Born  Veterans  Mean Travel Time  Median Household Income  \
0  1001             1.6      5922              26.2                    53682   
1  1003             3.6     19346              25.9                    50221   
2  1005             2.9      2120              24.6                    32911   
3  1007             1.2      1327              27.6                    36447   
4  1009             4.3      4540              33.9                    44145   

   Below Poverty Level  Total Number of Firms  % Black-owned Firms  \
0                 12.1                   4067                 15.2   
1                 13.9                  19035                  2.7   
2                 26.7                   1667                  0.0   
3                 18.1                   1385                 14.9   
4                 15.8                   4458                  0.0   

   % Asian-owned Firms  % Hispanic-owned Firms  % Women-owned Firms  \
0                  1.3                     0.7                 31.7   
1                  1.0                     1.3                 27.3   
2                  0.0                     0.0                 27.0   
3                  0.0                     0.0                  0.0   
4                  0.0                     0.0                 23.2   

   Manufacturers Shipments ($1000)  Retail Sales ($1000)  \
0                                0                598175   
1                          1410273               2966489   
2                                0                188337   
3                                0                124707   
4                           341544                319700   

   Retail Sales per Capita  Building permits  Population per Square Mile  \
0                    12003               131                        91.8   
1                    17166              1384                       114.6   
2                     6334                 8                        31.0   
3                     5804                19                        36.8   
4                     5622                 3                        88.9   

   Bernie Sanders  Hillary Clinton                    Most Votes  
0             544             2387  ('Votes', 'Hillary Clinton')  
1            2694             5290  ('Votes', 'Hillary Clinton')  
2             222             2567  ('Votes', 'Hillary Clinton')  
3             246              942  ('Votes', 'Hillary Clinton')  
4             395              564  ('Votes', 'Hillary Clinton')

In [3]:
file2 = "reps.csv"
primary_data2 = pd.read_csv(file2)
primary_data2.head()

fips  % Foreign Born  Veterans  Mean Travel Time  Median Household Income  \
0  1001             1.6      5922              26.2                    53682   
1  1003             3.6     19346              25.9                    50221   
2  1005             2.9      2120              24.6                    32911   
3  1007             1.2      1327              27.6                    36447   
4  1009             4.3      4540              33.9                    44145   

   Below Poverty Level  Total Number of Firms  % Black-owned Firms  \
0                 12.1                   4067                 15.2   
1                 13.9                  19035                  2.7   
2                 26.7                   1667                  0.0   
3                 18.1                   1385                 14.9   
4                 15.8                   4458                  0.0   

   % Asian-owned Firms  % Hispanic-owned Firms            ...              \
0                  1.3                     0.7            ...               
1                  1.0                     1.3            ...               
2                  0.0                     0.0            ...               
3                  0.0                     0.0            ...               
4                  0.0                     0.0            ...               

   Chris Christie  Donald Trump  Jeb Bush  John Kasich  Marco Rubio  \
0               0          5387         0          421         1785   
1               0         23618         0         2987         9703   
2               0          1710         0          123          498   
3               0          1959         0           84          444   
4               0          7390         0          337         1843   

   Mike Huckabee  Rand Paul  Rick Santorum  Ted Cruz  \
0              0          0              0      2482   
1              0          0              0      8571   
2              0          0              0       609   
3              0          0              0      1011   
4              0          0              0      3698   

                  Most Votes  
0  ('Votes', 'Donald Trump')  
1  ('Votes', 'Donald Trump')  
2  ('Votes', 'Donald Trump')  
3  ('Votes', 'Donald Trump')  
4  ('Votes', 'Donald Trump')  

[5 rows x 28 columns]

In [4]:
primary_data.columns

Index(['fips', '% Foreign Born', 'Veterans', 'Mean Travel Time',
       'Median Household Income', 'Below Poverty Level',
       'Total Number of Firms', '% Black-owned Firms', '% Asian-owned Firms',
       '% Hispanic-owned Firms', '% Women-owned Firms',
       'Manufacturers Shipments ($1000)', 'Retail Sales ($1000)',
       'Retail Sales per Capita', 'Building permits',
       'Population per Square Mile', 'Bernie Sanders', 'Hillary Clinton',
       'Most Votes'],
      dtype='object')

In [5]:
primary_data2.columns

Index(['fips', '% Foreign Born', 'Veterans', 'Mean Travel Time',
       'Median Household Income', 'Below Poverty Level',
       'Total Number of Firms', '% Black-owned Firms', '% Asian-owned Firms',
       '% Hispanic-owned Firms', '% Women-owned Firms',
       'Manufacturers Shipments ($1000)', 'Retail Sales ($1000)',
       'Retail Sales per Capita', 'Building permits',
       'Population per Square Mile', 'Ben Carson', 'Carly Fiorina',
       'Chris Christie', 'Donald Trump', 'Jeb Bush', 'John Kasich',
       'Marco Rubio', 'Mike Huckabee', 'Rand Paul', 'Rick Santorum',
       'Ted Cruz', 'Most Votes'],
      dtype='object')

In [6]:
 #Assign X (data) and y (target)

## BEGIN SOLUTION
X2 = primary_data2[['% Foreign Born', 'Veterans', 'Mean Travel Time',
       'Median Household Income', 'Below Poverty Level',
       'Total Number of Firms', '% Black-owned Firms', '% Asian-owned Firms',
       '% Hispanic-owned Firms', '% Women-owned Firms',
       'Manufacturers Shipments ($1000)', 'Retail Sales ($1000)',
       'Retail Sales per Capita', 'Building permits',
       'Population per Square Mile']]

y2 = primary_data2[['Most Votes']]
print(X2.shape, y2.shape)
### END SOLUTION

(2711, 15) (2711, 1)


In [7]:
# Assign X (data) and y (target)

## BEGIN SOLUTION
X = primary_data[['% Foreign Born', 'Veterans', 'Mean Travel Time',
       'Median Household Income', 'Below Poverty Level',
       'Total Number of Firms', '% Black-owned Firms', '% Asian-owned Firms',
       '% Hispanic-owned Firms', '% Women-owned Firms',
       'Manufacturers Shipments ($1000)', 'Retail Sales ($1000)',
       'Retail Sales per Capita', 'Building permits',
       'Population per Square Mile']]

y = primary_data[['Most Votes']]
print(X.shape, y.shape)
### END SOLUTION

(2798, 15) (2798, 1)


In [8]:
from sklearn.preprocessing import LabelEncoder

# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder2 = LabelEncoder()
label_encoder.fit(y)
label_encoder2.fit(y2)
encoded_y = label_encoder.transform(y)
encoded_y2 = label_encoder2.transform(y2)

C:\Users\cobin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\cobin\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
for label, original_class in zip(encoded_y, y):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

Original Class: Most Votes
Encoded Label: 2
------------


In [10]:
for label, original_class in zip(encoded_y2, y2):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

Original Class: Most Votes
Encoded Label: 1
------------


In [11]:
# Split the data into training and testing

### BEGIN SOLUTION
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, encoded_y, random_state=10)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, encoded_y2, random_state=10)
### END SOLUTION

In [12]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScater model and fit it to the training data
X_scaler = StandardScaler().fit(X_train)
X_scaler2 = StandardScaler().fit(X_train2)

C:\Users\cobin\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\cobin\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


In [13]:
# Transform the training and testing data using the X_scaler

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
X_train_scaled2 = X_scaler2.transform(X_train2)
X_test_scaled2 = X_scaler2.transform(X_test2)

C:\Users\cobin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\cobin\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.
C:\Users\cobin\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  """
C:\Users\cobin\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  


In [14]:
# from sklearn.preprocessing import LabelEncoder

# # Step 1: Label-encode data set
# label_encoder = LabelEncoder()
# label_encoder.fit(y)
# encoded_y = label_encoder.transform(y)
label_encoder.inverse_transform(y_test)

array(["('Votes', 'Hillary Clinton')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'Hillary Clinton')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'H

### One-hot encoding

In [15]:
from keras.utils import to_categorical

y_test_categorical = to_categorical(y_test)
one_hot_y = to_categorical(y_train)
one_hot_y


Using TensorFlow backend.


array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [16]:
y_test_categorical2 = to_categorical(y_test2)
one_hot_y2 = to_categorical(y_train2)
one_hot_y2

array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], dtype=float32)

# Democrat Model
#### deep neural network: 2 layers with 15 inputs, 30 hidden nodes, and 3 outputs

In [17]:
from keras.models import Sequential
from keras.layers import Dense

deep_model = Sequential()
deep_model.add(Dense(units=30, activation='relu', input_dim=15))
# deep_model.add(Dense(units=300, activation='relu'))
# deep_model.add(Dense(units=300, activation='relu'))
# deep_model.add(Dense(units=300, activation='relu'))
deep_model.add(Dense(units=30, activation='relu'))
deep_model.add(Dense(units=3, activation='softmax'))

Instructions for updating:
Colocations handled automatically by placer.


In [18]:
deep_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 30)                480       
_________________________________________________________________
dense_2 (Dense)              (None, 30)                930       
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 93        
Total params: 1,503
Trainable params: 1,503
Non-trainable params: 0
_________________________________________________________________


In [19]:
# # Load the model
# from keras.models import load_model
# deep_model = load_model("dems_model_trained.h5")

In [20]:
deep_model.compile(optimizer='adam',
                   loss='categorical_crossentropy',
                   metrics=['accuracy'])

deep_model.fit(
    X_train_scaled,
    one_hot_y,
    epochs=40,
    shuffle=True,
    verbose=2
)

Instructions for updating:
Use tf.cast instead.
Epoch 1/40
 - 1s - loss: 0.8379 - acc: 0.6130
Epoch 2/40
 - 0s - loss: 0.6538 - acc: 0.6749
Epoch 3/40
 - 0s - loss: 0.6070 - acc: 0.6930
Epoch 4/40
 - 0s - loss: 0.5924 - acc: 0.6930
Epoch 5/40
 - 0s - loss: 0.5818 - acc: 0.6897
Epoch 6/40
 - 0s - loss: 0.5758 - acc: 0.6954
Epoch 7/40
 - 0s - loss: 0.5720 - acc: 0.7040
Epoch 8/40
 - 0s - loss: 0.5662 - acc: 0.7054
Epoch 9/40
 - 0s - loss: 0.5631 - acc: 0.7059
Epoch 10/40
 - 0s - loss: 0.5618 - acc: 0.7112
Epoch 11/40
 - 0s - loss: 0.5563 - acc: 0.7140
Epoch 12/40
 - 0s - loss: 0.5606 - acc: 0.7107
Epoch 13/40
 - 0s - loss: 0.5570 - acc: 0.7083
Epoch 14/40
 - 0s - loss: 0.5519 - acc: 0.7121
Epoch 15/40
 - 0s - loss: 0.5512 - acc: 0.7159
Epoch 16/40
 - 0s - loss: 0.5476 - acc: 0.7092
Epoch 17/40
 - 0s - loss: 0.5467 - acc: 0.7164
Epoch 18/40
 - 0s - loss: 0.5425 - acc: 0.7231
Epoch 19/40
 - 0s - loss: 0.5415 - acc: 0.7164
Epoch 20/40
 - 0s - loss: 0.5402 - acc: 0.7164
Epoch 21/40
 - 0s - l

In [21]:
# Save the model
deep_model.save("dem_model_trained.h5")

# Republican Model
#### deep neural network: 2 layers with 15 inputs, 30 hidden nodes, and 5 outputs

In [22]:
deep_model2 = Sequential()
deep_model2.add(Dense(units=30, activation='relu', input_dim=15))
# deep_model2.add(Dense(units=400, activation='relu'))
# deep_model2.add(Dense(units=300, activation='relu'))
# deep_model2.add(Dense(units=200, activation='relu'))
deep_model2.add(Dense(units=30, activation='relu'))
deep_model2.add(Dense(units=5, activation='softmax'))

In [23]:
deep_model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 30)                480       
_________________________________________________________________
dense_5 (Dense)              (None, 30)                930       
_________________________________________________________________
dense_6 (Dense)              (None, 5)                 155       
Total params: 1,565
Trainable params: 1,565
Non-trainable params: 0
_________________________________________________________________


In [24]:
# Load the model
# from keras.models import load_model
# deep_model2 = load_model("rep_model_trained.h5")

In [25]:
deep_model2.compile(optimizer='adam',
                   loss='categorical_crossentropy',
                   metrics=['accuracy'])

deep_model2.fit(
    X_train_scaled2,
    one_hot_y2,
    epochs=40,
    shuffle=True,
    verbose=2
)

Epoch 1/40
 - 1s - loss: 1.1276 - acc: 0.6645
Epoch 2/40
 - 0s - loss: 0.7224 - acc: 0.7457
Epoch 3/40
 - 0s - loss: 0.6490 - acc: 0.7501
Epoch 4/40
 - 0s - loss: 0.6242 - acc: 0.7526
Epoch 5/40
 - 0s - loss: 0.6110 - acc: 0.7565
Epoch 6/40
 - 0s - loss: 0.5973 - acc: 0.7609
Epoch 7/40
 - 0s - loss: 0.5911 - acc: 0.7634
Epoch 8/40
 - 0s - loss: 0.5842 - acc: 0.7649
Epoch 9/40
 - 0s - loss: 0.5751 - acc: 0.7668
Epoch 10/40
 - 0s - loss: 0.5682 - acc: 0.7668
Epoch 11/40
 - 0s - loss: 0.5644 - acc: 0.7732
Epoch 12/40
 - 0s - loss: 0.5563 - acc: 0.7718
Epoch 13/40
 - 0s - loss: 0.5532 - acc: 0.7772
Epoch 14/40
 - 0s - loss: 0.5474 - acc: 0.7752
Epoch 15/40
 - 0s - loss: 0.5418 - acc: 0.7767
Epoch 16/40
 - 0s - loss: 0.5368 - acc: 0.7796
Epoch 17/40
 - 0s - loss: 0.5315 - acc: 0.7836
Epoch 18/40
 - 0s - loss: 0.5289 - acc: 0.7816
Epoch 19/40
 - 0s - loss: 0.5237 - acc: 0.7811
Epoch 20/40
 - 0s - loss: 0.5202 - acc: 0.7841
Epoch 21/40
 - 0s - loss: 0.5169 - acc: 0.7865
Epoch 22/40
 - 0s - lo

In [26]:
# Save the model
deep_model2.save("rep_model_trained.h5")

# Testing the models below

# Reps

In [27]:
model_loss, model_accuracy = deep_model2.evaluate(
    X_test_scaled2, y_test_categorical2, verbose=2)
print(
    f"Republican Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Republican Neural Network - Loss: 0.5835125514891295, Accuracy: 0.7433628318584071


0 = John Kasich
1 = Donald Trump
2 = Ben Carson
3 = Marco Rubio
4 = Ted Cruz

In [28]:
deep_model2.predict(X_test_scaled2)[:5]

array([[2.0384035e-04, 4.7952735e-01, 7.4195871e-03, 1.9310355e-04,
        5.1265603e-01],
       [3.1415229e-06, 4.1070914e-01, 2.2741052e-04, 8.1651183e-03,
        5.8089513e-01],
       [4.0238155e-03, 3.3403900e-01, 8.9695612e-03, 6.4391699e-03,
        6.4652848e-01],
       [7.2760879e-05, 9.4946975e-01, 2.1399322e-04, 1.5060833e-05,
        5.0228406e-02],
       [1.2564084e-03, 4.8564655e-01, 9.2286609e-02, 9.2681736e-04,
        4.1988367e-01]], dtype=float32)

In [29]:
label_encoder2.inverse_transform(y_test2)[:5]

array(["('Votes', 'Donald Trump')", "('Votes', 'Donald Trump')",
       "('Votes', 'Ted Cruz')", "('Votes', 'Donald Trump')",
       "('Votes', 'Donald Trump')"], dtype=object)

In [30]:
label_encoder2.inverse_transform(np.argmax(deep_model2.predict(X_test_scaled2), axis=1))[:41]

array(["('Votes', 'Ted Cruz')", "('Votes', 'Ted Cruz')",
       "('Votes', 'Ted Cruz')", "('Votes', 'Donald Trump')",
       "('Votes', 'Donald Trump')", "('Votes', 'Donald Trump')",
       "('Votes', 'Donald Trump')", "('Votes', 'Donald Trump')",
       "('Votes', 'Donald Trump')", "('Votes', 'Marco Rubio')",
       "('Votes', 'Ted Cruz')", "('Votes', 'Donald Trump')",
       "('Votes', 'Donald Trump')", "('Votes', 'Donald Trump')",
       "('Votes', 'Donald Trump')", "('Votes', 'Donald Trump')",
       "('Votes', 'Donald Trump')", "('Votes', 'Donald Trump')",
       "('Votes', 'Donald Trump')", "('Votes', 'Ted Cruz')",
       "('Votes', 'Donald Trump')", "('Votes', 'Ted Cruz')",
       "('Votes', 'Donald Trump')", "('Votes', 'Donald Trump')",
       "('Votes', 'Donald Trump')", "('Votes', 'Donald Trump')",
       "('Votes', 'Donald Trump')", "('Votes', 'Donald Trump')",
       "('Votes', 'Donald Trump')", "('Votes', 'Donald Trump')",
       "('Votes', 'Donald Trump')", "('Votes', 'Te

In [31]:
np.argmax(deep_model2.predict(X_test_scaled2), axis=1)

array([4, 4, 4, 1, 1, 1, 1, 1, 1, 3, 4, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 4,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 4, 4, 1, 4, 1, 4,
       1, 4, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1,
       1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       4, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 4, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 4, 1, 1, 4, 1, 4, 1, 1,
       4, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 4, 1, 4, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       4, 1, 4, 4, 4, 4, 1, 1, 1, 4, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 4, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 4, 1, 1, 1, 1, 4, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [32]:
y_test2

array([1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1, 4, 1, 1, 1, 1, 1, 1, 4, 4, 4,
       2, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 2, 1, 3, 1, 4, 1, 4,
       4, 1, 1, 1, 1, 4, 2, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1, 4, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 4, 4, 1, 4, 1, 1, 1, 1, 1, 1,
       4, 3, 1, 1, 1, 1, 4, 1, 1, 2, 1, 1, 1, 4, 1, 4, 1, 1, 4, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 4, 1, 4, 4, 1, 1, 1, 1, 4, 1, 4, 1, 1, 1, 4, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 4, 1, 1,
       4, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 4, 1, 4, 4, 1, 4, 1, 4, 1, 1,
       1, 1, 1, 1, 1, 1, 4, 1, 4, 1, 1, 1, 1, 4, 4, 1, 1, 1, 1, 4, 1, 1,
       1, 2, 1, 1, 1, 1, 4, 1, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1,
       1, 1, 4, 4, 1, 1, 1, 1, 1, 4, 1, 1, 4, 4, 1, 1, 4, 1, 1, 4, 1, 1,
       1, 1, 1, 4, 1, 1, 4, 1, 4, 1, 1, 1, 4, 1, 1, 1, 1, 1, 4, 1, 1, 1,
       4, 1, 1, 4, 1, 1, 1, 1, 4, 1, 1, 1, 2, 1, 1, 1, 4, 1, 1, 1, 1, 1,
       4, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1,

# Dems

In [33]:
model_loss, model_accuracy = deep_model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(f"Democrat Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Democrat Neural Network - Loss: 0.5854031416348049, Accuracy: 0.6771428574834552


0 = No Preference
1 = Bernie Sanders
2 = Hillary Clinton

In [34]:
deep_model.predict(X_test_scaled)[:5]

array([[6.6576337e-07, 1.0212541e-01, 8.9787394e-01],
       [3.3153368e-03, 4.4709814e-01, 5.4958659e-01],
       [4.4458293e-04, 5.4959488e-01, 4.4996062e-01],
       [5.0600208e-03, 6.7414790e-01, 3.2079208e-01],
       [1.9357961e-03, 5.7279384e-01, 4.2527041e-01]], dtype=float32)

In [35]:
label_encoder.inverse_transform(y_test)[:5]

array(["('Votes', 'Hillary Clinton')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Hillary Clinton')"], dtype=object)

In [36]:
label_encoder.inverse_transform(np.argmax(deep_model.predict(X_test_scaled), axis=1))[:5]

array(["('Votes', 'Hillary Clinton')", "('Votes', 'Hillary Clinton')",
       "('Votes', 'Bernie Sanders')", "('Votes', 'Bernie Sanders')",
       "('Votes', 'Bernie Sanders')"], dtype=object)

In [37]:
np.argmax(deep_model.predict(X_test_scaled), axis=1)

array([2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1,
       1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1,
       2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2,
       2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2,
       2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1,
       2, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 2, 1,
       2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1,
       1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 1,
       1, 2, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [38]:
y_test

array([2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1,
       1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1,
       2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1,
       1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1,
       2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1,
       2, 2, 1, 1, 2, 1, 2, 2, 2, 0, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2,
       1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2,
       2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1,
       2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1,